import type { AppConfig } from '../types/config'

export const DEFAULT_CONFIG: AppConfig = {
  app: {
    defaultVolume: 80,
    gaplessPlayback: 'yes',
    replaygain: 'track',
    notifications: true,
  },
  theme: {
    highlight: '#7dd3fc',
    subtle: '#6b7280',
    special: '#f472b6',
  },
  filters: {
    minDuration: 0,
    titles: [],
    genres: [],
    excludeFavorites: false,
  },
  columns: {
    songs: {
      trackNumber: true,
      title: true,
      artist: true,
      album: true,
      year: true,
      rating: true,
      duration: true,
    },
  },
  keybinds: {
    playback: {
      play_pause: ['space'],
      next: ['n'],
      prev: ['p'],
      volume_up: ['+', '='],
      volume_down: ['-'],
      loop: ['l'],
      shuffle: ['S'],
      rewind: ['<'],
      forward: ['>'],
      restart: ['.'],
      toggle_now_playing: ['M'],
    },
    navigation: {
      up: ['k', 'up'],
      down: ['j', 'down'],
      top: ['g'],
      bottom: ['G'],
      select: ['return'],
      shuffle_play: ['S-return'],
      filter_next: ['f'],
      filter_prev: ['F'],
      go_to_album: ['a'],
      go_to_artist: ['r'],
    },
    queue: {
      enqueue_last: ['q'],
      enqueue_next: ['Q'],
      remove: ['x'],
      clear: ['X'],
    },
    global: {
      tab_next: ['tab'],
      tab_prev: ['S-tab'],
      tab_1: ['1'],
      tab_2: ['2'],
      tab_3: ['3'],
      tab_4: ['4'],
      search: ['/'],
      star: ['*'],
      rate: ['R'],
      playlist_add: ['P'],
      help: ['?'],
      back: ['escape'],
      quit: ['Z'],
    },
  },
}
